name: puzzle_game
description: an app with multiple different puzzle games
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/words.txt
    - assets/sounds/click.wav
    - assets/sounds/correct.wav
    - assets/sounds/reset.mp3
